In [1]:
# Sauce: https://www.sharpsightlabs.com/blog/numpy-axes-explained/

import numpy as np

# Basically

axis number starts from 0.
In a 2D array, axis 0 runs down vertically,
while axis 1 runs right horizontally.

In [7]:
# Reshape

print('before reshape:')
print(np.arange(0, 6))

np_array_2d = np.arange(0, 6).reshape([2,3])
print('after reshape:')
print(np_array_2d)

before reshape:
[0 1 2 3 4 5]
after reshape:
[[0 1 2]
 [3 4 5]]


# Numpy sum()

In [8]:
# sum along axis 0
np.sum(np_array_2d, axis=0)

# sum along axis 1
np.sum(np_array_2d, axis=1)

array([3, 5, 7])

# Numpy concatenate()

In [12]:
np_array_1s = np.array([
  [1,1,1],
  [1,1,1]
])
np_array_9s = np.array([
  [9,9,9],
  [9,9,9]
])

np.concatenate([np_array_1s, np_array_9s], axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [13]:
np.concatenate([np_array_1s, np_array_9s], axis=1)

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

# Remember

## axis for all kinds of arrays start from 0

In [14]:
np.array([1,1,1]) # axis = 0

# In fact it is better to read it as a vector:
np.array([
  1,
  1,
  1,
])

array([1, 1, 1])

In [19]:
# concatenating 1d array
np_array_1s_1d = np.array([1,1,1])
np_array_9s_1d = np.array([9,9,9])

print(np_array_1s_1d)
print(np_array_9s_1d)

print('np.concatentate axis=0, result:')
print(np.concatenate([np_array_1s_1d, np_array_9s_1d], axis=0))
print("isn't it confusing? No, remember to treat the 1d arrays as VECTORS")

[1 1 1]
[9 9 9]
np.concatentate axis=0, result:
[1 1 1 9 9 9]
isn't it confusing? No, remember to treat the 1d arrays as VECTORS


# np.newaxis

## Promote xD array to (x+1)D array

In [28]:
np_1d = np.array([1,2,3,4])
print(np_1d)

print('shape of array:')
print(np_1d.shape)

# new axis
np_new_axis_at_0 = np_1d[np.newaxis, :]
np_new_axis_at_1 = np_1d[:, np.newaxis]

print('\nnew axis at 0:')
print(np_new_axis_at_0)
print('new shape:')
print(np_new_axis_at_0.shape)

print('\nnew axis at 1:')
print(np_new_axis_at_1)
print('new shape:')
print(np_new_axis_at_1.shape)


[1 2 3 4]
shape of array:
(4,)

new axis at 0:
[[1 2 3 4]]
new shape:
(1, 4)

new axis at 1:
[[1]
 [2]
 [3]
 [4]]
new shape:
(4, 1)
